working_directory = "C:/Users/kenny"
import = [ "~/.config/alacritty/catppuccin-macchiato.toml" ]

[font]
normal = { family = "Fira Code", style = "Regular" }
italic = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Regular" }

[keyboard]
bindings = [
	{key = "Space", mods = "Control", chars = "\u0000"},
]

[env]
TERM = "xterm-256color"
